## Assignment 3

### scraping news article from article_list.csv

In [2]:


# Import required libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

print("✅ Libraries imported successfully")

✅ Libraries imported successfully

In [ ]:
# having a look at the article_list csv
article_list = pd.read_csv('/workspaces/ECBS-5147-Data-Engineering-Cloud-Computing-Managed-AI-Services/serverless/project/articles_raw.csv', 
                 encoding='utf-8')
article_list[10:20]

,Source,Title,URL,Language,Unnamed: 4
10,Prothom Alo,BNP rethinks its approach to allies,https://en.prothomalo.com/bangladesh/politics/...,en,NaN
11,Prothom Alo,BNP’s Masuduzzaman quits race over 'security i...,https://en.prothomalo.com/bangladesh/9pkzu86yuv,en,NaN
12,Prothom Alo,"Meeting of 29 party allies, decision to sort t...",https://en.prothomalo.com/bangladesh/politics/...,en,NaN
13,Prothom Alo,66pc say BNP will win the most seats in the el...,https://en.prothomalo.com/bangladesh/jsto3ql5zk,en,NaN
14,Prothom Alo,BNP wants to push ahead with election plans am...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN
15,Prothom Alo,"Candidates busy in campaign, but Reza Kibria d...",https://en.prothomalo.com/bangladesh/politics/...,en,NaN
16,Prothom Alo,Those who seek to exploit crisis are enemies o...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN
17,Prothom Alo,BNP wants to make Tarique Rahman’s return “mem...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN
18,Prothom Alo,BNP in dilemma over implementation of reform r...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN
19,Prothom Alo,Is BNP stepping into trouble?,https://en.prothomalo.com/opinion/op-ed/pmyhye...,en,NaN

In [29]:
# scrape all daily star

all_daily_star = []
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) "
    + " Chrome/39.0.2171.95 Safari/537.36"
}

for i, url in enumerate(article_list["URL"][:10]):
    
    star_response = requests.get(url, headers=headers)
    daily_star = BeautifulSoup(star_response.content, "html.parser")
    
    title_star = daily_star.find("h1").get_text(strip= True)
    star_body = daily_star.find("article")
    star_paragraphs = star_body.find_all("p")
    star_text = "\n".join([p.get_text(strip=True) for p in star_paragraphs])
    all_daily_star.append(star_text)

In [30]:
# check if it worked
print(all_daily_star[0][:500]) # 0 for the first article
print(all_daily_star[3][:500]) # 3 for the third article

The interim government's revised election timeline with certain conditions has stirred cautious optimism as well as raised questions among  political parties.
While many parties including the BNP have welcomed the proposed  timeline -- mid-February next year --  concerns have emerged regarding how the decision was reached through discussions with only one party.
The BNP had long been demanding that the election be held by the year-end. It had been criticising the interim government for not unvei
Even though a week has passed since the announcement of the election schedule, BNP allies still do not know how many seats they might be allotted.
They said frustration is deepening within their ranks as the BNP has kept the seat-sharing issue hanging for so long.
The parties that were part of the simultaneous movement with the BNP also claimed the BNP did not hold any discussions with them before unveiling its nominees in most constituencies.
In efforts to assuage the allies, the BNP held one-t

In [31]:
# scrape all prothomalo

all_prothomalo = []

for i, url in enumerate(article_list["URL"][10:]):
    
    protho_response = requests.get(url, headers=headers)
    prothomalo = BeautifulSoup(protho_response.content, "html.parser")
    
    prothomalo_title = prothomalo.find("h1").get_text(strip= True)
    prothomalo_body = prothomalo.find_all("div", class_="story-element-text")
    prothomalo_text = "\n".join([p.get_text(strip=True) for p in prothomalo_body])

    all_prothomalo.append(prothomalo_text)

In [32]:
# check if it worked
print(all_prothomalo[0][:500])
print(all_prothomalo[5][:500])
print(all_prothomalo[15][:500])

The BNP’s earlier thinking on forming an alliance or contesting elections jointly with its partners in the simultaneous movement is undergoing some change.Relevant responsible sources say the BNP will not form an electoral alliance with its partner parties in the election. There will, however, be seat-sharing arrangements in some constituencies. As part of this, the BNP will not nominate candidates in the constituencies of several top leaders of allied parties. In addition, if the BNP has alread
In the chilly winter weather, electioneering has gained momentum in Habiganj’s four constituencies ahead of the 13th parliamentary election. Nominated candidates from BNP, Jamaat-e-Islami, and other parties are taking part daily in rallies, processions, courtyard meetings, and various campaign programs.Since the election schedule was announced, campaigning has intensified further. Not only town areas, but even remote rural areas of the district are now covered with candidates’ banners, festoons,
প্রতিটি আসনে নির্বাচনী এজেন্ট, পোলিং এজেন্ট ও একজন সোশ্যাল মিডিয়া ম্যানেজার ঠিক করছে বিএনপি। তাদের জন্য শিগগির প্রশিক্ষণ কার্যক্রম শুরু করা হবে। আগামী জানুয়ারির মাঝামাঝি পর্যন্ত প্রশিক্ষণ কার্যক্রম শেষ করা হবে। এ লক্ষ্যে ধানের শীষ প্রতীকের সব প্রার্থীর কাছ থেকে তালিকা সংগ্রহ করা হচ্ছে। প্রার্থীরা একজন নির্বাচনী এজেন্ট, দুজন পোলিং এজেন্ট ও একজন সোশ্যাল মিডিয়া ম্যানেজারের নাম-ঠিকানা ও হোয়াটসঅ্যাপ নম্বরসহ বিস্তারিত তথ্য কেন্দ্রে জমা দিচ্ছেন।জানা গেছে, নির্বাচনী মাঠে দলীয় কর্মসূচি প্রচারের পাশাপাশি

### Translating from Bengali to English

In [33]:
from pprint import PrettyPrinter
import boto3

print("📚 Setting up the environment...")
pp = PrettyPrinter(indent=2)
translate = boto3.client("translate")
print("✅ Environment setup complete!")
print(f"🌍 Using AWS region: {translate.meta.region_name}")

📚 Setting up the environment...
✅ Environment setup complete!
🌍 Using AWS region: eu-west-1

In [36]:
import sys

print("🔄 Translating from Bengali to English...")
translation = []

for i in all_prothomalo[10:]:
    # Calculate the actual byte size AWS will see
    byte_size = len(i.encode('utf-8'))

    if byte_size > 10000:
        # We split the string into chunks of 3000 characters. 
        # Since Bengali is ~3 bytes/char, 3000 chars is ~9000 bytes (safe)
        chunk_size = 3000
        
        # Split into 3 parts (adjust range if articles are even longer)
        p1 = i[:chunk_size]
        p2 = i[chunk_size:chunk_size*2]
        p3 = i[chunk_size*2:chunk_size*3]
        p4 = i[chunk_size*3:]
        
        # Get translations and extract ['TranslatedText']
        resp1 = translate.translate_text(Text=p1, SourceLanguageCode="bn", TargetLanguageCode="en")
        resp2 = translate.translate_text(Text=p2, SourceLanguageCode="bn", TargetLanguageCode="en")
        
        texts = [resp1['TranslatedText'], resp2['TranslatedText']]
        
        # Only call if p3 actually has text
        if p3.strip():
            resp3 = translate.translate_text(Text=p3, SourceLanguageCode="bn", TargetLanguageCode="en")
            texts.append(resp3['TranslatedText'])
        
        if p4.strip():
            resp4 = translate.translate_text(Text=p4, SourceLanguageCode="bn", TargetLanguageCode="en")
            texts.append(resp4['TranslatedText'])
            
        response = "\n".join(texts)

    else:
        resp = translate.translate_text(Text=i, SourceLanguageCode="bn", TargetLanguageCode="en")
        response = resp['TranslatedText']

    translation.append(response)

# Note: Using pp.pprint might still show some encoding characters in the terminal
#import pprint
# pp = pprint.PrettyPrinter(indent=4)
pp.pprint(translation)

🔄 Translating from Bengali to English...
[ 'With the 13th National Assembly elections ahead, the electoral momentum of '
  'candidates from different parties in the six parliamentary seats in '
  'Sirajganj is steadily gaining momentum. After the announcement of the '
  'schedule, election-centered discussions and debates are also taking place '
  'among the general public. In some seats, the campaign of the rival '
  'candidates prevails, in some places the party clashes. Somewhere there are '
  'discussions about the change of leaders. The electoral heat is increasing '
  'day by day as candidates nominated by different parties take to the field '
  'in the six seats in the district. There has been some party discontent in '
  "the two seats over the BNP's nomination. Former MP Manzoor Kader is in "
  'talks to become the NCP candidate after not receiving the BNP nomination '
  'for the Sirajganj-5 seat. However, the candidates nominated by the BNP have '
  'taken to the field to campaign with activists and supporters. Islamic '
  'leaders and activists have also taken to the field with party candidates in '
  'every seat. The candidates of the two parties are spending a busy time in '
  'field meetings, marches, road meetings and public relations. Posters and '
  'banners have been hung all over the city from the village. The new '
  "political party, the National Citizens' Party (NCP), has so far fielded "
  'candidates for four seats in the district. Potential candidates of the '
  'Islamic Movement Bangladesh, the Communist Party of Bangladesh (CPB), the '
  'Socialist Party of Bangladesh (Bassad) are also campaigning in various '
  'seats. In the end, local voters are looking at who can reflect '
  'organizational strength and public support on the ballot box.\n'
  'At the time of the announcement of the nominations in the first phase, the '
  'BNP left the seat vacant. In a second phase, the party nominated former '
  'president of the Kazipur Upzilla BNP, Selim Reza, on December 4. The '
  'nominees for the BNP were District BNP member vocalist Rumana Morshed '
  'Konkchappa and District BNP Vice President Nazmul Hasan Talukdar. Leaders '
  'and activists said there was some dissatisfaction among the local BNP over '
  'the nomination. However, BNP candidate Salim Reza said in the first light '
  'that the central BNP had nominated him for the seat after evaluating the '
  'grassroots leaders and workers. He wants to overcome all the conflicts and '
  'bring everyone with him and give the seat to the team. In this seat, Aamir '
  "Shahinur Alam is the party's candidate in Jamaat district. He began "
  'meetings after the nomination was confirmed. Abu Zafar received the '
  "nomination of the Islamic Movement for the seat. The CPB's Abdul Baki and "
  'the Abu Sama government of Basd are also campaigning.\n'
  'Iqbal Hasan Mahmoud Tuku, a member of the BNP Standing Committee, has '
  "become the party's candidate for the Sirajganj — 2 seat. The Jamaat's "
  "nomination was received by the party's district secretary, Muhammad Zahidul "
  'Islam. Candidates from various parties, including BNP, Jamaat, have already '
  'started talking about activists and supporters on the field. BNP candidate '
  'Iqbal Hasan Mahmoud said, “After a long time, the people of the country are '
  'eagerly waiting to exercise their franchise. We are making recommendations '
  "to the people on what to do with the people if we are elected. ' Jamaat "
  "candidate Mohammad Jahidul Islam said at First Light: 'We are going to "
  "people's door-to-door in the field and voting. I meet them in different "
  "ways. By doing so, I'm extremely optimistic about people's love. ' The "
  'Islamic movement has nominated Md. To Mahabbullah. In addition, Anwar '
  "Hossain Reza, a member of the party's central committee from the CPB, and "
  'Abdullah Al Mamun of Basd are campaigning to be candidates.\n'
  'District BNP Information & Research\n'
  'Editor Aynul Hawk received a party nomination here. BNP leader Abdul Mannan '
  'Talukdar was a member of parliament in 1991, 1996 and 2001. After his '
  'death, his son Rahid Mannan Lellin was this time the BNP nominee. A part of '
  'the party remains inactive on the electoral field if he is not nominated. '
  "AANUL HAWK SAID AT FIRST LIGHT, 'I HAVE ALREADY TAKEN TO THE POLLING FIELD "
  'WITH MY PARTY LEADERS-STAFF. People have not been able to exercise their '
  'franchise for a long time. If fair and fair elections are held this time, '
  'voters with joy like Eid Day will spontaneously win me by huge votes. '
  "That's my belief. ' The party nominated Mohammad Abdus Samad, a member of "
  "the Islamic Central Labour Council here in Jama'a. The NCP has been "
  "nominated by the team's joint chief coordinator Dilshana Parul. In the "
  'seat, the candidate of the Islamic movement, Gazi Ainul Haq. In addition, '
  "Mostafa Nurul Amin, general editor of the CPB's district committee, and "
  'Palash Kumar Ghosh of Basd are also on the field.\n'
  'Former MP M Akbar Ali has been nominated as the BNP candidate for the seat. '
  'However, after announcing his candidacy for the seat, supporters of former '
  'Ullapara Upzilla BNP member Azad Hossain marched and manhandled demanding a '
  "change in the nomination. 'Mr Akbar Ali has not been seen on the field in "
  "the last 16 years, 'Azad Hossain said in the first light. That's why there "
  'was no case in his name. At that time, I led BNP politics from the field. I '
  'am a defendant in 70 cases. I went to jail 26 times. Why would the team '
  "underestimate me now? ' M Akbar Ali said, “I have been nominated to "
  'properly assess the expectations of the people of the grasslands. People '
  "will win me by a huge vote, Insha Allah. ' Here, Jamaat's central assistant "
  "secretary general, Rafikul Islam Khan, has been given the party's "
  'nomination. Shahzahan Ali, Amir Professor of Ullapara Upzilla Jamaat, said '
  'people were ready to vote for Rafikul Islam Khan. Wherever he goes, people '
  "surround him. The NCP's nominee for the seat was the party's central senior "
  "joint member Duti Aranya Chowdhury. 'I am keeping in constant contact with "
  "people in my area (Ullapara), 'he said. ABDUL HAKIM, THE PARTY'S UPZILLA "
  'PRESIDENT, IS RUNNING FROM THE BANGLADESH COMMUNIST PARTY.\n'
  'Former MP Manzur Kader has left the BNP and is in talks for the Sirajganj-5 '
  'seat as the NCP candidate. He was hoping for the BNP nomination for the '
  'seat. However, the BNP has nominated Rajshahi divisional co-organisational '
  'editor Amirul Islam Khan Alim. Speaking to people close to Manzoor Kader, '
  "Manzoor Kader recently resigned as a member of the BNP's National Executive "
  'Committee and as a primary member of the team, citing personal reasons. He '
  'then joined the NCP and was nominated for the seat. After receiving the NCP '
  'nomination, Manzur Kader wrote in a Facebook post, “Believing in this '
  'advancement and the idea of new politics in Bangladesh and in the struggle '
  "to establish people's rights, as a former student of Dhaka University, I am "
  'unable to involve myself as a former student of Dhaka University. With '
  'regard to the issue, I joined the National Citizens Party (NCP) and got '
  'nominated in the national parliament elections in the constituency of '
  "Sirajganj-5 (Belkuchi-Chauhali). ' He added, “I believe that NCP can bring "
  'forward a new generation of leadership and institutionalize democracy in '
  'Bangladesh and shape the future of the country.\n'
  "To make amends. '\n"
  'BNP candidate Amirul Islam Khan Alim is campaigning in the area with '
  'leaders and activists. “Insha Allah is responding much more than I expected '
  'from the people of the area,” he said. Jamaat candidate Ali Alam is in the '
  'seat. He is the Naive Amir of the District Jamaat. “We have already '
  'completed 100 per cent of election preparations, including campaigning on '
  'the ground,” he said. Now people are just waiting for the vote. Insha Allah '
  "we are extremely optimistic in this seat. ' In addition, Islamic Movement "
  'candidate Sheikh Mohammed Nurun Nabi and potential candidate for the '
  "People's Rights Council, Sohrawardi Hossain, are also campaigning. Mothoor "
  'Rahman could run for the Bangladesh Communist Party.\n'
  'THE PARTY HAS NOMINATED DISTRICT BNP ADVISER MA MUHIT FOR THE SEAT. He is '
  'the son of former Deputy Prime Minister Prayat M. A. Motin. “We want to '
  'forget all hatred and work for people together,” said M.A. Muhit. As a '
  'candidate in the next election, I am getting a huge response from the '
  "people. The grassroots people are with us. ' Jamaat candidate Mizanur "
  'Rahman is in the seat. He is the Amir of Shahzadpur Upzilla Jamaat. The NCP '
  "has been nominated by the party's central joint member secretary SM Saif "
  'Mustafiz. In addition, Mesbah Uddin, an adviser to the district committee '
  'of the Islamic Movement, and Anwar Hossain, the leader of the Bassad, are '
  'candidates.',
  'In Lakshmipur, a BNP leader named Belal Hossain was accused of setting fire '
  'to the house of a BNP leader by locking doors and pouring petrol. During '
  'this time, a seven-year-old girl of the BNP leader died in a house fire. In '
  'addition, the BNP leader and two of his other daughters were caught in the '
  'fire. The incident took place in the Sutargopta area of Charmansa village '
  'of Bhavaniganj Union in Sadar Upzela on Friday night yesterday. Belal '
  'Hossain is a co-organisational editor of Bhavaniganj Union BNP in '
  'Lakshmipur and a fertiliser and pesticide trader at Sutargopta market.\n'
  'The name of the child who died in the fire was Ayesha Akhtar. The three '
  'accused were Belal Hossain (50) and his two daughters, Veethi Akhtar (17) '
  'and Smriti Akhtar (14). Among them, Beethi Akhtar and Smriti Akhtar have '
  'been sent to the National Institute of Burn and Plastic Surgery for '
  'treatment. Belal is being treated at the headquarters hospital. The fire '
  "also burned Belal Hossain's house to ashes. The family and local residents "
  "said Belal's family had all fallen asleep after dinner. At around 2pm, the "
  'thieves locked the door and set the house on fire. Gasoline was poured and '
  'set on fire, causing it to quickly spread around.\n'
  "'The terrorists poured petrol and set fire, 'said Hachibur Rahman, joint "
  'convener of the district BNP. The door was previously locked. Terrorists '
  'have done this purposefully. We demand the swift arrest of those involved '
  "in the incident. ' Ranjit Kumar Das, station officer of Lakshmipur Fire "
  'Service, said a child was rescued from the scene after receiving the news. '
  'In addition, three people were rescued and taken to hospital in a critical '
  'condition. The condition of both of them is suspicious. You can see how the '
  'fire started.\n'
  'The Acting Officer (OC) of Lakshmipur Sadar Model Police, Md. WAHID PARVEZ '
  'SAID A SLEEPING BABY BURNED TO DEATH IN THE FIRE. It remains to be seen '
  'whether someone deliberately set fire to the house.',
  'BNP Acting Chairman Tarek Rahman said he expects to see free and impartial '
  'national elections under the interim government. He said the government '
  "must respect the people's fair demands. There is no room for arrogance or "
  'anger on the part of the government here. Tarek Rahman spoke at the 18th '
  "founding anniversary meeting of the National People's Party (NPP) in Dhaka "
  'on Sunday, joining virtually from London at the Diplomatic Engineers '
  'Institution Milnayata. Calling for constructive criticism of the '
  'government, Tariq Rahman said citizens should continue to issue '
  'constructive criticism of the government, whether it is a government '
  'elected by direct popular vote, an interim government or a caretaker '
  'government. The people of the country are not at the mercy of the '
  'government. He said the BNP delegation met with Chief Adviser Professor '
  'Muhammad Yunus on Saturday. At the meeting, the chief adviser was '
  'reiterated by the BNP about the national elections scheduled for next '
  'December.\n'
  'Noting the stagnation in domestic and foreign investment due to the lack of '
  'a stable democratic government in the country, the acting chairman of BNP '
  'said that there is a kind of instability among people of different classes '
  'and professions due to an uncertain political and economic situation. That '
  'is why people of different classes and professions are coming down the '
  'highway with different demands every day. But sadly, though true, there is '
  'no one to listen to their claims at the moment. Tarek Rahman believes that '
  'the interim government has created a stalemate in revenue collection by '
  'pushing NBR reforms just before the budget passes. He said it was not a '
  "good thing for the economy. It is everyone's belief that an accountable "
  'democratic government can play the most effective role in dealing with such '
  'a situation.\n'
  'Referring to an ongoing process of reform, Tarek Rahman said, “There is no '
  'such thing as little or too much reform. Reform is a continuous process at '
  'the behest of the state and politics. But practical reform is more '
  'important than fundamental reform.” Noting that the interim government is '
  'not accountable, Tarek Rahman said there may not be a crisis of moral and '
  'political legitimacy of the interim government. However, this government is '
  'not accountable to the people. Therefore, for moral reasons, the '
  "government's precise plans need to be clear to the public. In the end, no "
  'plan will be effective or sustainable by leaving people in the dark or '
  'political parties in limbo.',
  'BNP will hire trains on seven routes to bring leaders and supporters from '
  'all over the country to Dhaka on the occasion of the return of the acting '
  'chairman of the BNP, Tariq Rahman. The party sent a letter to the Ministry '
  'of Railways on Thursday seeking permission to reserve those seven special '
  'trains with extra compartments on the night of December 24. The letter was '
  'given by Ruhul Kabir Rizvi, senior joint general secretary of BNP, stating '
  'that certain rents would be paid as per government policies.\n'
  "BNP's letter referred to trains on seven routes. They are Cox's "
  'Bazar-Dhaka, Sylet-Dhaka, Jamalpur-Mymensingh-Dhaka, Tangail-Dhaka, '
  'ChapainBabganj-Rajshahi-Dhaka, Panchgar-Nilfamari-Parbatipur-Dhaka and Kuri '
  'Gram-Rangpur-Dhaka route. The letter said BNP acting chairman Tarek Rahman '
  'will return to Dhaka from the UK on December 25. A large number of students '
  'from all over the country will arrive in Dhaka to welcome him. To '
  'facilitate their arrival, BNP intends to reserve trains for various routes '
  'on the day of December 24. The fixed rent will be paid according to '
  'government policy.\n'
  'In a letter to the Secretary of the Ministry of Railways, BNP specifically '
  'requested the Ministry of Railways to reserve one special train with extra '
  'compartments on each route.',
  'In Narayanganj-5 (city-port) seat, BNP-nominated candidate Mohammad '
  'Masudzaman has again announced his participation in the elections due to '
  "the 'security issue'. He made the decision on Friday afternoon in the face "
  'of pressure from party leaders, activists and supporters. On Friday '
  'afternoon, leaders and supporters marched from the Khanpur area of the city '
  'and surrounded his organization model group in the Talla area. They also '
  'shouted slogans demanding that he return to the election process. He later '
  'left the office and made the announcement. Leaders and workers from '
  'district and metropolitan BNP and allied organizations were present.\n'
  'In an exchange meeting with journalists at the Narayanganj Press Club on '
  'December 16, Masuduzman announced his withdrawal from the upcoming '
  "elections 'due to security concerns and family pressure'. His announcement "
  'sparked outrage among party leaders and staff. They had been meeting for '
  'several days to bring him back. In a speech to the leaders and workers on '
  'Friday, Masuduzman said, “Mourn for us today. One of our brothers, Osman '
  "Hadi, has died. May Allah make him a martyr.” Recalling Osman Hadid's "
  'political role, he said that while many political parties were walking in '
  'the opposite direction of elections, Hadi led young people to the polls and '
  'educated the nation through life.\n'
  'Commenting on his previous decision, Masuduzman said, “By announcing no '
  'elections on December 16, I have harmed my party, the acting chairman of '
  'the party, Tariq Rahman, and the leaders of the standing committee. For '
  'this I apologize unconditionally. The team is bigger than the individual, '
  'the country is bigger than the team. We are before me, the country before '
  'us, the people before power, Bangladesh before everyone else. From this '
  'stage today, I am announcing — I agree with the decisions taken by the '
  'acting chairman of the party, Tariq Rahman and the BNP. I have been '
  "nominated by BNP and will participate in the elections Insha Allah. ' He "
  'added: “From now on, you are my family, you are my safety. There are no '
  "more security concerns. I'll bet on my life.”",
  'BNP appoints election agents, polling agents and a social media manager in '
  'each seat. Training activities will be started soon for them. The training '
  'will be completed by mid-January. To this end, a list is being collected '
  'from all the candidates for the rice sheesh symbol. Candidates are '
  'submitting details to the centre, including the name and WhatsApp number of '
  'an election agent, two polling agents and a social media manager. It is '
  'reported that the emphasis will be on promoting party programs on the '
  'electoral field, as well as creating a counter-boycott of opposing '
  'candidates. A social media manager will be trained in each seat.\n'
  'According to the announced schedule, the election campaign will begin on '
  'January 22. Before that, the BNP wants to complete the training of its '
  'party election workers. According to party sources, Democracy International '
  '(DI), an international organisation involved in participation and training '
  'in the global election process, has recently been given a list of more than '
  'half a hundred people for electoral training by the BNP. Everyone on the '
  'list will be trained in several steps. Training has already been carried '
  'out in two phases. The event will end in mid-January. Trained individuals '
  'will train seat-based polling agents. In addition, BNP is offering '
  "'Election Campaign Management' training to the final candidates from "
  'Wednesday. This training workshop will end on Saturday. Later, '
  'district-based master training activities will begin. They will provide all '
  'of them with central training. ARAFAT BILLAH KHAN, THE FORMER UNION LEADER '
  'OF THE STUDENT GROUP ASSOCIATED WITH THE EVENT, SAID WHAT WILL THE RICE '
  'SEED CANDIDATE SAY IN THE CAMPAIGN? What will be mentioned in the campaign? '
  'What narrative can opposition candidates possibly make? Workshops will be '
  'organized on what counter narratives can be.\n'
  'Meanwhile, the acting chairman of the BNP, Tarek Rahman, exchanged views '
  'with the party candidates for the second day on Thursday. About 100 '
  'candidates took part in the exchange meeting. Tarek Rahman joins the '
  'meeting virtually from London. At the exchange meeting, they were given '
  'various guidelines on compliance with the election code of conduct and the '
  'campaign strategy of the vote. In particular, family cards, farmer cards, '

## translations to dataframe

In [ ]:
# 1. Align the original text with your DataFrame
# This assumes articles_list matches the row order of your CSV (0-9 Daily Star, 10-29 Prothom Alo)
article_list['og_text'] = all_daily_star + all_prothomalo
article_list[:5]

,Source,Title,URL,Language,Unnamed: 4,og_text
0,The Daily Star,New Polls Timing BNP upbeat process irks Jamaa...,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,The interim government's revised election time...
1,The Daily Star,BNP announces candidates for 36 more constitue...,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,BNP has announced its candidates for 36 more c...
2,The Daily Star,Seat-sharing snub riles BNP allies,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,Discontent runs deep among BNP's partners as t...
3,The Daily Star,Seat sharing BNP still keeps allies hanging,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,Even though a week has passed since the announ...
4,The Daily Star,"Election to be tough for BNP, bigger test if v...",https://www.thedailystar.net/news/bangladesh/p...,en,NaN,The next national election will be tough for t...
5,The Daily Star,Old habits die hard? BNP’s response,https://www.thedailystar.net/opinion/views/new...,en,NaN,"An opinion piece titled ""BNP's notes of dissen..."
6,The Daily Star,BNP at 47: Caught between prospects and perils,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,The BNP has survived Sheikh Hasina's 15-year r...
7,The Daily Star,BNP’s show of force on Airport Road and a poli...,https://www.thedailystar.net/opinion/views/new...,en,NaN,The former Prime Minister Khaleda Zia on Tuesd...
8,The Daily Star,Fulfilling Uprising's Aspirations: Correction ...,https://www.thedailystar.net/opinion/editorial...,en,NaN,After having weathered a difficult 15 years in...
9,The Daily Star,Cases against its candidates a concern for BNP,https://www.thedailystar.net/news/bangladesh/p...,en,NaN,The BNP has alerted its election candidates th...
10,Prothom Alo,BNP rethinks its approach to allies,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,The BNP’s earlier thinking on forming an allia...
11,Prothom Alo,BNP’s Masuduzzaman quits race over 'security i...,https://en.prothomalo.com/bangladesh/9pkzu86yuv,en,NaN,Citing security concerns amid the recent situa...
12,Prothom Alo,"Meeting of 29 party allies, decision to sort t...",https://en.prothomalo.com/bangladesh/politics/...,en,NaN,The 29 parties allied with the BNP in the simu...
13,Prothom Alo,66pc say BNP will win the most seats in the el...,https://en.prothomalo.com/bangladesh/jsto3ql5zk,en,NaN,Most people in the country believe the Banglad...
14,Prothom Alo,BNP wants to push ahead with election plans am...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,A month after announcing party candidates for ...
15,Prothom Alo,"Candidates busy in campaign, but Reza Kibria d...",https://en.prothomalo.com/bangladesh/politics/...,en,NaN,"In the chilly winter weather, electioneering h..."
16,Prothom Alo,Those who seek to exploit crisis are enemies o...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,Bangladesh Nationalist Party (BNP) Secretary G...
17,Prothom Alo,BNP wants to make Tarique Rahman’s return “mem...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,Bangladesh Nationalist Party (BNP) wants to ma...
18,Prothom Alo,BNP in dilemma over implementation of reform r...,https://en.prothomalo.com/bangladesh/politics/...,en,NaN,The Bangladesh Nationalist Party (BNP) has fou...
19,Prothom Alo,Is BNP stepping into trouble?,https://en.prothomalo.com/opinion/op-ed/pmyhye...,en,NaN,"""Election"" is the key word of present times, w..."
20,প্রথম আলো,বিএনপি ছেড়ে এনসিপির প্রার্থী হয়ে আলোচনায় সা...,https://www.prothomalo.com/politics/juller8ad4,bn,NaN,ত্রয়োদশ জাতীয় সংসদ নির্বাচন সামনে রেখে সিরাজগঞ...
21,প্রথম আলো,"‘দরজায় তালা লাগিয়ে’ বিএনপি নেতার ঘরে আগুন, ঘ...",https://www.prothomalo.com/bangladesh/district...,bn,NaN,লক্ষ্মীপুরে দরজায় তালা লাগিয়ে ও পেট্রল ঢেলে বে...
22,প্রথম আলো,সরকারের মান-অভিমানের সুযোগ নেই: তারেক রহমান,https://www.prothomalo.com/politics/hpuqtw02xd,bn,NaN,অন্তর্বর্তী সরকারের অধীনে অবাধ ও নিরপেক্ষ জাতী...
23,প্রথম আলো,"তারেক রহমানের প্রত্যাবর্তন, সাতটি ট্রেন ভাড়া ...",https://www.prothomalo.com/politics/an2qglrigg,bn,NaN,বিএনপির ভারপ্রাপ্ত চেয়ারম্যান তারেক রহমানের প্...
24,প্রথম আলো,নারায়ণগঞ্জে সরে দাঁড়ানো বিএনপি প্রার্থী মাসু...,https://www.prothomalo.com/bangladesh/district...,bn,NaN,‘নিরাপত্তা ইস্যুর’ কথা বলে নির্বাচন থেকে সরে দ...
25,প্রথম আলো,ভোটের প্রচারকৌশল ও ভোট নিয়ে প্রশিক্ষণের বড় ক...,https://www.prothomalo.com/politics/sulmb2nbnt,bn,NaN,"প্রতিটি আসনে নির্বাচনী এজেন্ট, পোলিং এজেন্ট ও ..."
26,প্রথম আলো,চট্টগ্রামে এক আসনে মনোনয়নপত্র নিলেন বিএনপির ত...,https://www.prothomalo.com/bangladesh/district...,bn,NaN,ত্রয়োদশ জাতীয় সংসদ নির্বাচনে চট্টগ্রামের বিভিন...
27,প্রথম আলো,"কোন আসনে বিএনপির প্রার্থী কে, দেখে নিন",https://www.prothomalo.com/politics/fshzbhqbdx,bn,NaN,আগামী জাতীয় সংসদ নির্বাচনে ২৩৭ আসনে প্রার্থী ঘ...
28,প্রথম আলো,এক কোটি ‘সৎ মানুষের’ খোঁজ পাবে কি বিএনপি,https://www.prothomalo.com/opinion/column/0ziw...,bn,NaN,আওয়ামী লীগ সরকারের আমলে একটি কবিতার পঙ্‌ক্তি ব...
29,প্রথম আলো,কার ওপর ভরসা করছে বিএনপি,https://www.prothomalo.com/opinion/column/nkxg...,bn,NaN,বাংলাদেশ রাজনৈতিকভাবে এতটা বিভক্ত যে কোনো দুজন...

In [38]:

# 2. Define the translation function with your chunking logic
def translate_logic(row):
    text = row['og_text']
    # Use 'Language' (case-sensitive) as per your CSV
    lang = row['Language']
    
    # Logic 1: If English, copy-paste original
    if lang == "en":
        return text
    
    # Logic 2: If Bengali, translate (with chunking if needed)
    if lang == "bn":
        byte_size = len(text.encode('utf-8'))
        
        # Safe size for AWS Translate (10,000 bytes)
        if byte_size <= 10000:
            resp = translate.translate_text(Text=text, SourceLanguageCode="bn", TargetLanguageCode="en")
            return resp['TranslatedText']
        
        else:
            # Chunking logic for longer Bengali articles
            chunk_size = 3000
            # Split text into chunks of 3000 chars
            chunks = [text[i:i + chunk_size] for i in range(0, len(text), chunk_size)]
            
            translated_parts = []
            for chunk in chunks:
                if chunk.strip(): # Only translate if there is actual text
                    resp = translate.translate_text(
                        Text=chunk, 
                        SourceLanguageCode="bn", 
                        TargetLanguageCode="en"
                    )
                    translated_parts.append(resp['TranslatedText'])
            
            return "\n".join(translated_parts)
            
    return text  # Fallback for any other cases

# 3. Create the new column by applying the function
print("🔄 Processing and translating articles...")
article_list['translated_text'] = article_list.apply(translate_logic, axis=1)

# 4. Save the results
article_list.to_csv("articles_final.csv", index=False)
print("✅ Done! Saved to articles_final.csv")

🔄 Processing and translating articles...
✅ Done! Saved to articles_final.csv

In [ ]:
# 4. Save the results
#del article_list['Unnamed: 4']
article_list

,Source,Title,URL,Language,og_text,translated_text
0,The Daily Star,New Polls Timing BNP upbeat process irks Jamaa...,https://www.thedailystar.net/news/bangladesh/p...,en,The interim government's revised election time...,The interim government's revised election time...
1,The Daily Star,BNP announces candidates for 36 more constitue...,https://www.thedailystar.net/news/bangladesh/p...,en,BNP has announced its candidates for 36 more c...,BNP has announced its candidates for 36 more c...
2,The Daily Star,Seat-sharing snub riles BNP allies,https://www.thedailystar.net/news/bangladesh/p...,en,Discontent runs deep among BNP's partners as t...,Discontent runs deep among BNP's partners as t...
3,The Daily Star,Seat sharing BNP still keeps allies hanging,https://www.thedailystar.net/news/bangladesh/p...,en,Even though a week has passed since the announ...,Even though a week has passed since the announ...
4,The Daily Star,"Election to be tough for BNP, bigger test if v...",https://www.thedailystar.net/news/bangladesh/p...,en,The next national election will be tough for t...,The next national election will be tough for t...
5,The Daily Star,Old habits die hard? BNP’s response,https://www.thedailystar.net/opinion/views/new...,en,"An opinion piece titled ""BNP's notes of dissen...","An opinion piece titled ""BNP's notes of dissen..."
6,The Daily Star,BNP at 47: Caught between prospects and perils,https://www.thedailystar.net/news/bangladesh/p...,en,The BNP has survived Sheikh Hasina's 15-year r...,The BNP has survived Sheikh Hasina's 15-year r...
7,The Daily Star,BNP’s show of force on Airport Road and a poli...,https://www.thedailystar.net/opinion/views/new...,en,The former Prime Minister Khaleda Zia on Tuesd...,The former Prime Minister Khaleda Zia on Tuesd...
8,The Daily Star,Fulfilling Uprising's Aspirations: Correction ...,https://www.thedailystar.net/opinion/editorial...,en,After having weathered a difficult 15 years in...,After having weathered a difficult 15 years in...
9,The Daily Star,Cases against its candidates a concern for BNP,https://www.thedailystar.net/news/bangladesh/p...,en,The BNP has alerted its election candidates th...,The BNP has alerted its election candidates th...
10,Prothom Alo,BNP rethinks its approach to allies,https://en.prothomalo.com/bangladesh/politics/...,en,The BNP’s earlier thinking on forming an allia...,The BNP’s earlier thinking on forming an allia...
11,Prothom Alo,BNP’s Masuduzzaman quits race over 'security i...,https://en.prothomalo.com/bangladesh/9pkzu86yuv,en,Citing security concerns amid the recent situa...,Citing security concerns amid the recent situa...
12,Prothom Alo,"Meeting of 29 party allies, decision to sort t...",https://en.prothomalo.com/bangladesh/politics/...,en,The 29 parties allied with the BNP in the simu...,The 29 parties allied with the BNP in the simu...
13,Prothom Alo,66pc say BNP will win the most seats in the el...,https://en.prothomalo.com/bangladesh/jsto3ql5zk,en,Most people in the country believe the Banglad...,Most people in the country believe the Banglad...
14,Prothom Alo,BNP wants to push ahead with election plans am...,https://en.prothomalo.com/bangladesh/politics/...,en,A month after announcing party candidates for ...,A month after announcing party candidates for ...
15,Prothom Alo,"Candidates busy in campaign, but Reza Kibria d...",https://en.prothomalo.com/bangladesh/politics/...,en,"In the chilly winter weather, electioneering h...","In the chilly winter weather, electioneering h..."
16,Prothom Alo,Those who seek to exploit crisis are enemies o...,https://en.prothomalo.com/bangladesh/politics/...,en,Bangladesh Nationalist Party (BNP) Secretary G...,Bangladesh Nationalist Party (BNP) Secretary G...
17,Prothom Alo,BNP wants to make Tarique Rahman’s return “mem...,https://en.prothomalo.com/bangladesh/politics/...,en,Bangladesh Nationalist Party (BNP) wants to ma...,Bangladesh Nationalist Party (BNP) wants to ma...
18,Prothom Alo,BNP in dilemma over implementation of reform r...,https://en.prothomalo.com/bangladesh/politics/...,en,The Bangladesh Nationalist Party (BNP) has fou...,The Bangladesh Nationalist Party (BNP) has fou...
19,Prothom Alo,Is BNP stepping into trouble?,https://en.prothomalo.com/opinion/op-ed/pmyhye...,en,"""Election"" is the key word of present times, w...","""Election"" is the key word of present times, w..."
20,প্রথম আলো,বিএনপি ছেড়ে এনসিপির প্রার্থী হয়ে আলোচনায় সা...,https://www.prothomalo.com/politics/juller8ad4,bn,ত্রয়োদশ জাতীয় সংসদ নির্বাচন সামনে রেখে সিরাজগঞ...,With the 13th National Assembly elections ahea...
21,প্রথম আলো,"‘দরজায় তালা লাগিয়ে’ বিএনপি নেতার ঘরে আগুন, ঘ...",https://www.prothomalo.com/bangladesh/district...,bn,লক্ষ্মীপুরে দরজায় তালা লাগিয়ে ও পেট্রল ঢেলে বে...,"In Lakshmipur, a BNP leader named Belal Hossai..."
22,প্রথম আলো,সরকারের মান-অভিমানের সুযোগ নেই: তারেক রহমান,https://www.prothomalo.com/politics/hpuqtw02xd,bn,অন্তর্বর্তী সরকারের অধীনে অবাধ ও নিরপেক্ষ জাতী...,BNP Acting Chairman Tarek Rahman said he expec...
23,প্রথম আলো,"তারেক রহমানের প্রত্যাবর্তন, সাতটি ট্রেন ভাড়া ...",https://www.prothomalo.com/politics/an2qglrigg,bn,বিএনপির ভারপ্রাপ্ত চেয়ারম্যান তারেক রহমানের প্...,BNP will hire trains on seven routes to bring ...
24,প্রথম আলো,নারায়ণগঞ্জে সরে দাঁড়ানো বিএনপি প্রার্থী মাসু...,https://www.prothomalo.com/bangladesh/district...,bn,‘নিরাপত্তা ইস্যুর’ কথা বলে নির্বাচন থেকে সরে দ...,"In Narayanganj-5 (city-port) seat, BNP-nominat..."
25,প্রথম আলো,ভোটের প্রচারকৌশল ও ভোট নিয়ে প্রশিক্ষণের বড় ক...,https://www.prothomalo.com/politics/sulmb2nbnt,bn,"প্রতিটি আসনে নির্বাচনী এজেন্ট, পোলিং এজেন্ট ও ...","BNP appoints election agents, polling agents a..."
26,প্রথম আলো,চট্টগ্রামে এক আসনে মনোনয়নপত্র নিলেন বিএনপির ত...,https://www.prothomalo.com/bangladesh/district...,bn,ত্রয়োদশ জাতীয় সংসদ নির্বাচনে চট্টগ্রামের বিভিন...,Candidates have started collecting nominations...
27,প্রথম আলো,"কোন আসনে বিএনপির প্রার্থী কে, দেখে নিন",https://www.prothomalo.com/politics/fshzbhqbdx,bn,আগামী জাতীয় সংসদ নির্বাচনে ২৩৭ আসনে প্রার্থী ঘ...,The BNP has announced candidates for 237 seats...
28,প্রথম আলো,এক কোটি ‘সৎ মানুষের’ খোঁজ পাবে কি বিএনপি,https://www.prothomalo.com/opinion/column/0ziw...,bn,আওয়ামী লীগ সরকারের আমলে একটি কবিতার পঙ্‌ক্তি ব...,The verse of a poem became quite popular durin...
29,প্রথম আলো,কার ওপর ভরসা করছে বিএনপি,https://www.prothomalo.com/opinion/column/nkxg...,bn,বাংলাদেশ রাজনৈতিকভাবে এতটা বিভক্ত যে কোনো দুজন...,Bangladesh is so politically divided that aski...

In [ ]:
# save the results
article_list.to_csv("articles_final.csv", index=False)
print("✅ Done! Saved to articles_final.csv")