# AWS Translate – translate Bangla Prothom Alo articles to English

In [1]:
# Import required libraries and set up our environment
import pandas as pd
from pprint import PrettyPrinter

import boto3
import time

print("📚 Setting up the environment...")
pp = PrettyPrinter(indent=2)
translate = boto3.client("translate")
print("✅ Environment setup complete!")
print(f"🌍 Using AWS region: {translate.meta.region_name}")
print("✅ AWS Translate client ready")

📚 Setting up the environment...
✅ Environment setup complete!
🌍 Using AWS region: eu-west-1
✅ AWS Translate client ready

In [2]:
# Load the dataset

print("📄 Loading articles.csv...")

df = pd.read_csv("articles.csv")

print("✅ Dataset loaded")
print("Columns:", list(df.columns))
print("Language counts:")
print(df["language"].value_counts())

📄 Loading articles.csv...
✅ Dataset loaded
Columns: ['source', 'language', 'url', 'article_text', 'text_orig_ln', 'translated_text']
Language counts:
language
en    18
bn    12
Name: count, dtype: int64

In [3]:
# Preserve original text and store translations
if "text_orig_ln" not in df.columns:
    df["text_orig_ln"] = pd.NA

if "translated_text" not in df.columns:
    df["translated_text"] = pd.NA

In [4]:

print("🔁 Translating Bangla articles to English...")

for idx, row in df.iterrows():

    if row["language"] == "bn" and isinstance(row["article_text"], str):

        try:
            df.at[idx, "text_orig_ln"] = row["article_text"]

            response = translate.translate_text(
                Text=row["article_text"][:5000],
                SourceLanguageCode="bn",
                TargetLanguageCode="en"
            )

            df.at[idx, "translated_text"] = response["TranslatedText"]
            print(f"✅ Translated row {idx}")

            time.sleep(0.2)

        except Exception as e:
            print(f"❌ Translation failed at row {idx}: {str(e)}")

    elif row["language"] == "en":
        df.at[idx, "translated_text"] = row["article_text"]

🔁 Translating Bangla articles to English...
✅ Translated row 10
✅ Translated row 11
✅ Translated row 12
✅ Translated row 13
✅ Translated row 14
✅ Translated row 15
✅ Translated row 16
✅ Translated row 17
✅ Translated row 18
✅ Translated row 21
✅ Translated row 24
✅ Translated row 26

In [5]:
print("💾 Saving translated dataset...")

df.to_csv("articles.csv", index=False)

print("✅ Translation complete and saved")

💾 Saving translated dataset...
✅ Translation complete and saved

In [6]:
df[["language", "translated_text"]].head(30)

   language                                    translated_text
0        en  The interim government's revised election time...
1        en  BNP has announced its candidates for 36 more c...
2        en  Discontent runs deep among BNP's partners as t...
3        en  Even though a week has passed since the announ...
4        en  The next national election will be tough for t...
5        en  An opinion piece titled "BNP's notes of dissen...
6        en  The BNP has survived Sheikh Hasina's 15-year r...
7        en  The former Prime Minister Khaleda Zia on Tuesd...
8        en  After having weathered a difficult 15 years in...
9        en  The BNP has alerted its election candidates th...
10       bn  A BNP a. Relevant responsible sources say the ...
11       bn  Citing security concerns amid the recent situa...
12       bn  The 29 parties allied with the BNP in the simu...
13       bn  Most people in the country believe the Banglad...
14       bn  A month after announcing party candidates for ...
15       bn  In the chilly winter weather, elections have g...
16       bn  Segretario Generale Mirza Fakhrul Islam Alamgi...
17       bn  The Bangladesh Nationalist Party (BNP) wants t...
18       bn  The Bangladesh Nationalist Party (BNP) has fou...
19       en  "Election" is the key word of present times, w...
20       en  ত্রয়োদশ জাতীয় সংসদ নির্বাচন সামনে রেখে সিরাজগঞ...
21       bn  In Lakshmipur, a BNP leader named Belal Hossai...
22       en  অন্তর্বর্তী সরকারের অধীনে অবাধ ও নিরপেক্ষ জাতী...
23       en  বিএনপির ভারপ্রাপ্ত চেয়ারম্যান তারেক রহমানের প্...
24       bn  In Narayanganj-5 (city-port) seat, BNP-nominat...
25       en  প্রতিটি আসনে নির্বাচনী এজেন্ট, পোলিং এজেন্ট ও ...
26       bn  Candidates have started collecting nominations...
27       en  আগামী জাতীয় সংসদ নির্বাচনে ২৩৭ আসনে প্রার্থী ঘ...
28       en  আওয়ামী লীগ সরকারের আমলে একটি কবিতার পঙ্‌ক্তি ব...
29       en  বাংলাদেশ রাজনৈতিকভাবে এতটা বিভক্ত যে কোনো দুজন...

In [7]:
df[df["language"] == "bn"][["language", "article_text", "translated_text"]].head()

,language,article_text,translated_text
10,bn,The BNP’s earlier thinking on forming an allia...,A BNP a. Relevant responsible sources say the ...
11,bn,Citing security concerns amid the recent situa...,Citing security concerns amid the recent situa...
12,bn,The 29 parties allied with the BNP in the simu...,The 29 parties allied with the BNP in the simu...
13,bn,Most people in the country believe the Banglad...,Most people in the country believe the Banglad...
14,bn,A month after announcing party candidates for ...,A month after announcing party candidates for ...